---
:api_key: c80b0c359c8968f779f0e37810d51c03
:password: 4b04e07eec43802944080a34bc5d9a4b
:store: urban-zen-aspen.myshopify.com
:theme_id:
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
